train:
  _target_: src.datasets.DigiCamDataset
  dataset_name: bezzam/DigiCam-Mirflickr-MultiMask-10K
  split: train
  shuffle_index: True
test:
  _target_: src.datasets.DigiCamDataset
  dataset_name: bezzam/DigiCam-Mirflickr-MultiMask-10K
  split: test
