defaults:
  - model: unrolled
  - writer: cometml
  - metrics: lensless
  - datasets: digicam
  - dataloader: example
  - transforms: none
  - _self_
normalize: true
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-2
loss_function:
  _target_: src.loss.Loss
trainer:
  log_step: 10
  n_epochs: 10
  epoch_len: 300
  device_tensors: ["lensless", "lensed", "psf"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "max test_PSNR" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
